# fetchAPIの使い方2

## OSSで解決する

### Axios
- 人気のデータフェッチングライブラリ
- レスポンス情報を自動でerrorハンドリングしてくれる
```js filename="axios"
try {
  const { data } = await axios.get('/user')
} catch (err) {
  // Handle issues via error.response.*
}
```

### Redaxios
- 一言でいうと「よりモダンなAxios」
- Axiosはいいライブラリだがデータフェッチングだけにしてはサイズが大きすぎる
- Axiosが`11kb`に対し、Redaxiosなら`1kb`以下
- 使い方が同じでimport文を変更するだけ
```js filename="Redaxios"
import axios from 'redaxios'
// use as you would normally
```


### Wretch
```js filename="関数型プログラミング的に記述できる"
const user = await wretch("/user")
  .get()
  // Handle error cases in a more human-readable way
  .notFound(error => { /* ... */ })
  .unauthorized(error => { /* ... */ })
  .error(418, error => { /* ... */ })
  .res(response => /* ... */)
  .catch(error => { /* uncaught errors */ })
```


## 正しくデータを書く
```js filename="どこが間違っているか？"
const res = await fetch('/user', {
  method: 'POST',
  body: { name: 'Steve Sewell', company: 'Builder.io' }
})
```

- `body`はJSONシリアライズしよう
```js
const res = await fetch('/user', {
  method: 'POST',
  // ✅ We must JSON-serialize this body
  body: JSON.stringify({ name: 'Steve Sewell', company: 'Builder.io' })
})
```

- `headers`を渡そう
<br/>→バックエンドは`headers`が無ければそもそも受け取らない言語・フレームワークが多い
```js
const res = await fetch('/user', {
  headers: {
    // ✅ If we are sending serialized JSON, we should set the Content-Type:
    'Content-Type': 'application/json'
  },
  method: 'POST',
  body: JSON.stringify({ name: 'Steve Sewell', company: 'Builder.io' })
})
```


## 自動的にJSONをサポートする
- 毎回`headers`や`JSON.stringify`をするならwrapしてしまう
```js
const isPlainObject = value => value?.constructor === Object

export async function myFetch(...options) {
  let initOptions = options[1]
  // If we specified a RequestInit for fetch
  if (initOptions?.body) {
    // If we have passed a body property and it is a plain object or array
    if (Array.isArray(initOptions.body) || isPlainObject(initOptions.body)) {
      // Create a new options object serializing the body and ensuring we
      // have a content-type header
      initOptions = {
        ...initOptions,
        body: JSON.stringify(initOptions.body),
        headers: {
          'Content-Type': 'application/json',
          ...initOptions.headers
        }
      }
    }
  }

  const res = await fetch(...initOptions)
  if (!res.ok) {
    throw new ResponseError('Bad fetch response', res)
  }
  return res
}
```
※ 良い共通化(アブストラクション)はテンプレ作業を省き、エラーを防ぐ。呼び出し側に依存しない事が重要。
↓
```js filename="使う"
const res = await myFetch('/user', {
  method: 'POST',
  body: { name: 'Steve Sewell', company: 'Builder.io' }
})
```


### OSSならWrapperしてくれる
```js filename="axios Redaxios"
const res = await axios.post('/user', {
  name: 'Steve Sewell', company: 'Builder.io' 
})
```

```js filename="Wretch"
const res = await wretch('/user').post({ 
  name: 'Steve Sewell', company: 'Builder.io' 
})
```


## Wrapperの型安全
- typeScriptを使おう
- `const initOption = someArray[1]`のような予測は基本的によろしくない
```js filename="wrapper with TS"
const isPlainObject = (value: unknown) => value?.constructor === Object

class ResponseError extends Error {
  response: Response

  constructor(message: string, res: Response) {
    super(message)
    this.response = res
  }
}

export async function myFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  let initOptions = init
  // If we specified a RequestInit for fetch
  if (initOptions?.body) {
    // If we have passed a body property and it is a plain object or array
    if (Array.isArray(initOptions.body) || isPlainObject(initOptions.body)) {
      // Create a new options object serializing the body and ensuring we
      // have a content-type header
      initOptions = {
        ...initOptions,
        body: JSON.stringify(initOptions.body),
        headers: {
          "Content-Type": "application/json",
          ...initOptions.headers,
        },
      }
    }
  }

  const res = await fetch(input, initOptions)
  if (!res.ok) {
    throw new ResponseError("Bad response", res)
  }
  return res
}
```

## catchしたerrはunknownタイプを使おう(23年現在では歴史の話)
- ※デフォルトで`unknown`だが、以前は`any`
- `any`だと`err.respose.status`などを持っているかわからない
- `err`にはどんな型もありえるため以下のように型アノテーションをしてはいけない
```js
try {
  const res = await myFetch
} catch (err: ResponseError) {
  // 🚩 TS error 1196: Catch clause variable type annotation must be 'any' or 'unknown' if specified
}
```
→ errには`unknown`を使おう(今はデフォルト)

```js
try {
  const res = await myFetch('/user')
  const user = await res.body()
} catch (err: unknown) {
  if (err instanceof ResponseError) {
    // Nice and type-safe!
    switch (err.response.status) { ... }
  } else {
    throw new Error('An unknown error occured when fetching the user', {
      cause: err
    })
}
```
→ `instanceof`を使っているから開発時にオブジェクトのプロパティを決定してくれる


### エラーハンドリングも共通化する
```js {14}
try {
  const res = await myFetch('/user')
  const user = await res.body()
} catch (err) {
  if (err instanceof ResponseError) {
    if (err.response.status === 404) {
      // Special logic unique to this call where we want to handle this status,
      // like to say on a 404 that we seem to not have this user
      return
    }
  }
  // ⬇️ Handle anything else that we don't need special logic for, and just want
  // our default handling
  handleError(err)
  return
}
```


```js
export function handleError(err: unkown) {
  // Safe to our choice of logging service
  saveToALoggingService(err);

  if (err instanceof ResponseError) {
    switch (err.response.status) {
      case 401:
        // Prompt the user to log back in
        showUnauthorizedDialog()
        break;
      case 500: 
        // Show user a dialog to apologize that we had an error and to 
        // try again and if that doesn't work contact support
        showErrorDialog()
        break;
      default:
        // Show 
        throw new Error('Unhandled fetch response', { cause: err })
    }
  } 
  throw new Error('Unknown fetch error', { cause: err })
}
```

### with OSS
```js filename="axios redaxios"
try {
  const { data: user } = await axios.get('/user')
} catch (err) {
  if (axios.isAxiosError(err)) {
    if (err.response.status === 404) {
      // Special not found logic
      return
    }
  }
  // Catch anything else with our default handler
  handleError(err)
  return
}
```

```js filename="Wretch"
try {
  const res = await wretch.get('/user')
    .notFound(() => { /* Special not found logic */ })
  const user = await res.body()
} catch (err) {
  // Catch anything else with our default handler
  handleError(err);
  return;
}
```